spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hafeeztsd/config-repo
          username: hafeeztsd
          password: abdulhafeez123
          searchPaths: '{application}'
          force-pull: true
          
server:
  port: 8888
  
   